# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

# Coverage targets
coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

  # Configure precision
  precision: 2
  round: down
  range: 60...100

# Comment configuration for PRs
comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - main
    - develop

# Flag configuration for frontend/backend coverage
flags:
  frontend:
    paths:
      - packages/frontend/
    carryforward: true
  backend:
    paths:
      - packages/backend/
    carryforward: true

# Ignore patterns
ignore:
  - 'node_modules'
  - '**/node_modules'
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '**/__tests__/**'
  - '**/*.stories.tsx'
  - '**/stories/**'
  - '**/test/**'
  - '**/tests/**'
  - 'e2e/**'
  - '**/*.config.ts'
  - '**/*.config.js'
  - '**/vite.config.*'
  - '**/vitest.config.*'
  - '**/playwright.config.*'
  - '**/eslint.config.*'
  - 'packages/frontend/dist/**'
  - 'packages/backend/dist/**'
  - 'packages/frontend/public/**'
  - 'packages/frontend/src/vite-env.d.ts'

# GitHub Checks
github_checks:
  annotations: true

# Require CI to pass before sending
require_ci_to_pass: true

# Status checks
codecov:
  notify:
    after_n_builds: 2 # Wait for both frontend and backend coverage
    require_ci_to_pass: true
