/**
 * useServiceWorker Hook
 *
 * Manages service worker registration, updates, and offline status.
 * Provides user-friendly prompts for updates and offline state detection.
 *
 * @module hooks/useServiceWorker
 */

import { useState, useEffect, useCallback } from 'react';

/**
 * Service worker registration result
 */
export interface ServiceWorkerState {
  /** Whether service worker is supported */
  isSupported: boolean;
  /** Whether service worker is registered */
  isRegistered: boolean;
  /** Whether app is offline */
  isOffline: boolean;
  /** Whether an update is available */
  needsUpdate: boolean;
  /** Whether the app needs a refresh after update */
  needsRefresh: boolean;
  /** Current registration object */
  registration: ServiceWorkerRegistration | null;
  /** Error if registration failed */
  error: Error | null;
}

/**
 * Service worker hook options
 */
export interface UseServiceWorkerOptions {
  /** Path to service worker (default: '/sw.js') */
  swUrl?: string;
  /** Callback when update is available */
  onNeedRefresh?: () => void;
  /** Callback when offline detection changes */
  onOfflineChange?: (isOffline: boolean) => void;
  /** Callback on registration error */
  onError?: (error: Error) => void;
  /** Callback when registered successfully */
  onRegistered?: (registration: ServiceWorkerRegistration) => void;
  /** Auto-reload on update (default: false) */
  autoReload?: boolean;
}

/**
 * Hook return type
 */
export interface UseServiceWorkerReturn extends ServiceWorkerState {
  /** Update the service worker and reload */
  updateServiceWorker: () => Promise<void>;
  /** Check for updates manually */
  checkForUpdates: () => Promise<void>;
  /** Dismiss the update notification */
  dismissUpdate: () => void;
}

/**
 * Custom hook for managing service worker registration and updates
 */
export function useServiceWorker(options: UseServiceWorkerOptions = {}): UseServiceWorkerReturn {
  const { onNeedRefresh, onOfflineChange, onError, onRegistered, autoReload = false } = options;

  const [state, setState] = useState<ServiceWorkerState>({
    isSupported: typeof navigator !== 'undefined' && 'serviceWorker' in navigator,
    isRegistered: false,
    isOffline: typeof navigator !== 'undefined' ? !navigator.onLine : false,
    needsUpdate: false,
    needsRefresh: false,
    registration: null,
    error: null,
  });

  // Handle offline/online status
  useEffect(() => {
    if (typeof window === 'undefined') return;

    const handleOnline = () => {
      setState((prev) => ({ ...prev, isOffline: false }));
      onOfflineChange?.(false);
    };

    const handleOffline = () => {
      setState((prev) => ({ ...prev, isOffline: true }));
      onOfflineChange?.(true);
    };

    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);

    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, [onOfflineChange]);

  // Register service worker on mount
  useEffect(() => {
    if (!state.isSupported) return;

    let cancelled = false;

    const registerSW = async () => {
      try {
        // Import the virtual module generated by vite-plugin-pwa
        const { registerSW } = await import('virtual:pwa-register');

        const updateSW = registerSW({
          immediate: true,
          onNeedRefresh() {
            if (cancelled) return;
            setState((prev) => ({ ...prev, needsUpdate: true, needsRefresh: true }));
            onNeedRefresh?.();

            if (autoReload) {
              updateSW(true);
            }
          },
          onOfflineReady() {
            if (cancelled) return;
            setState((prev) => ({ ...prev, isRegistered: true }));
          },
          onRegistered(registration) {
            if (cancelled || !registration) return;
            setState((prev) => ({
              ...prev,
              isRegistered: true,
              registration,
            }));
            onRegistered?.(registration);

            // Check for updates every 30 minutes
            setInterval(
              () => {
                registration.update();
              },
              30 * 60 * 1000
            );
          },
          onRegisterError(error) {
            if (cancelled) return;
            const err = error instanceof Error ? error : new Error(String(error));
            setState((prev) => ({ ...prev, error: err }));
            onError?.(err);
          },
        });

        // Store updateSW in state for later use
        if (!cancelled) {
          (window as unknown as { __updateSW?: (reload?: boolean) => Promise<void> }).__updateSW =
            updateSW;
        }
      } catch (error) {
        if (cancelled) return;
        const err = error instanceof Error ? error : new Error(String(error));
        setState((prev) => ({ ...prev, error: err }));
        onError?.(err);
      }
    };

    registerSW();

    return () => {
      cancelled = true;
    };
  }, [state.isSupported, onNeedRefresh, onError, onRegistered, autoReload]);

  // Update service worker
  const updateServiceWorker = useCallback(async () => {
    const updateSW = (window as unknown as { __updateSW?: (reload?: boolean) => Promise<void> })
      .__updateSW;

    if (updateSW) {
      await updateSW(true);
    } else {
      // Fallback: reload the page
      window.location.reload();
    }
  }, []);

  // Check for updates manually
  const checkForUpdates = useCallback(async () => {
    if (state.registration) {
      await state.registration.update();
    }
  }, [state.registration]);

  // Dismiss update notification
  const dismissUpdate = useCallback(() => {
    setState((prev) => ({ ...prev, needsUpdate: false }));
  }, []);

  return {
    ...state,
    updateServiceWorker,
    checkForUpdates,
    dismissUpdate,
  };
}

export default useServiceWorker;
